### ISSUE TITLE
Require unique content hashes for NFT-Editions

### ISSUE THREAD

**Issue by nickadamson** [ourzora/nft-editions#7]
Apologies if this was already considered, but it might be a good idea to enforce unique content hashes, like core/Media.sol.

For contract storage `mapping(bytes32 => bool) private _contentHashes;`

Then in createEdition():
```
require(
    _contentHashes[_imageHash] == false,
    "Media: a token has already been created with this content hash"
);

...

_contentHashes[_imageHash] = true;
```

**Comment by iainnash** [comment]
The SHA-256 hash hasn't proven to be a reasonable restriction for uniqueness since:
1. it cannot be verified/created on-chain
2. it can be changed by changing any byte in the source content
3. burned content cannot be re-created if there's an issue with the mint on the creator side
