### ISSUE TITLE
`totalSupply` call would be helpful

### ISSUE THREAD

**Issue by l3wi** [ourzora/nft-editions#9]
Sorry if this was already considered but a `totalSupply` function would be useful for a few reasons:
- Check if the edition is still mintable: `editionSize > totalSupply`
- if `editonSize` is 0, get how many have been minted so far
- Easily get % of supply owned by a single address: `balanceOf / totalSupply`

Cheers 🍻

**Comment by iainnash** [comment]
Merged into develop
